//go:build !ignore_autogenerated

/*
Copyright 2024 The Kubernetes Incident Investigator Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CausalSignals) DeepCopyInto(out *CausalSignals) {
	*out = *in
	if in.UnboundPVCNames != nil {
		in, out := &in.UnboundPVCNames, &out.UnboundPVCNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CausalSignals.
func (in *CausalSignals) DeepCopy() *CausalSignals {
	if in == nil {
		return nil
	}
	out := new(CausalSignals)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectionError) DeepCopyInto(out *CollectionError) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectionError.
func (in *CollectionError) DeepCopy() *CollectionError {
	if in == nil {
		return nil
	}
	out := new(CollectionError)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerEvidence) DeepCopyInto(out *ContainerEvidence) {
	*out = *in
	if in.ResourceLimits != nil {
		in, out := &in.ResourceLimits, &out.ResourceLimits
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ResourceRequests != nil {
		in, out := &in.ResourceRequests, &out.ResourceRequests
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LivenessProbe != nil {
		in, out := &in.LivenessProbe, &out.LivenessProbe
		*out = new(ProbeSummary)
		**out = **in
	}
	if in.ReadinessProbe != nil {
		in, out := &in.ReadinessProbe, &out.ReadinessProbe
		*out = new(ProbeSummary)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerEvidence.
func (in *ContainerEvidence) DeepCopy() *ContainerEvidence {
	if in == nil {
		return nil
	}
	out := new(ContainerEvidence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerLogEvidence) DeepCopyInto(out *ContainerLogEvidence) {
	*out = *in
	if in.Lines != nil {
		in, out := &in.Lines, &out.Lines
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerLogEvidence.
func (in *ContainerLogEvidence) DeepCopy() *ContainerLogEvidence {
	if in == nil {
		return nil
	}
	out := new(ContainerLogEvidence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CorrelatedEvidence) DeepCopyInto(out *CorrelatedEvidence) {
	*out = *in
	if in.CorrelatedAt != nil {
		in, out := &in.CorrelatedAt, &out.CorrelatedAt
		*out = (*in).DeepCopy()
	}
	if in.CausalSignals != nil {
		in, out := &in.CausalSignals, &out.CausalSignals
		*out = new(CausalSignals)
		(*in).DeepCopyInto(*out)
	}
	if in.LogPatterns != nil {
		in, out := &in.LogPatterns, &out.LogPatterns
		*out = new(LogPatterns)
		(*in).DeepCopyInto(*out)
	}
	if in.ChainPatterns != nil {
		in, out := &in.ChainPatterns, &out.ChainPatterns
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CorrelatedEvidence.
func (in *CorrelatedEvidence) DeepCopy() *CorrelatedEvidence {
	if in == nil {
		return nil
	}
	out := new(CorrelatedEvidence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DependencyEvidence) DeepCopyInto(out *DependencyEvidence) {
	*out = *in
	if in.PVCs != nil {
		in, out := &in.PVCs, &out.PVCs
		*out = make([]PVCEvidence, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ImagePullSecretNames != nil {
		in, out := &in.ImagePullSecretNames, &out.ImagePullSecretNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SchedulingConstraints != nil {
		in, out := &in.SchedulingConstraints, &out.SchedulingConstraints
		*out = new(SchedulingConstraints)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DependencyEvidence.
func (in *DependencyEvidence) DeepCopy() *DependencyEvidence {
	if in == nil {
		return nil
	}
	out := new(DependencyEvidence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosisFinding) DeepCopyInto(out *DiagnosisFinding) {
	*out = *in
	if in.SupportingEvidence != nil {
		in, out := &in.SupportingEvidence, &out.SupportingEvidence
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosisFinding.
func (in *DiagnosisFinding) DeepCopy() *DiagnosisFinding {
	if in == nil {
		return nil
	}
	out := new(DiagnosisFinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosisResult) DeepCopyInto(out *DiagnosisResult) {
	*out = *in
	if in.EvaluatedAt != nil {
		in, out := &in.EvaluatedAt, &out.EvaluatedAt
		*out = (*in).DeepCopy()
	}
	if in.Primary != nil {
		in, out := &in.Primary, &out.Primary
		*out = new(DiagnosisFinding)
		(*in).DeepCopyInto(*out)
	}
	if in.ContributingFactors != nil {
		in, out := &in.ContributingFactors, &out.ContributingFactors
		*out = make([]DiagnosisFinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AlternativeHypotheses != nil {
		in, out := &in.AlternativeHypotheses, &out.AlternativeHypotheses
		*out = make([]DiagnosisFinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosisResult.
func (in *DiagnosisResult) DeepCopy() *DiagnosisResult {
	if in == nil {
		return nil
	}
	out := new(DiagnosisResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventEvidence) DeepCopyInto(out *EventEvidence) {
	*out = *in
	if in.FirstTime != nil {
		in, out := &in.FirstTime, &out.FirstTime
		*out = (*in).DeepCopy()
	}
	if in.LastTime != nil {
		in, out := &in.LastTime, &out.LastTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventEvidence.
func (in *EventEvidence) DeepCopy() *EventEvidence {
	if in == nil {
		return nil
	}
	out := new(EventEvidence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvidenceSnapshot) DeepCopyInto(out *EvidenceSnapshot) {
	*out = *in
	if in.CollectedAt != nil {
		in, out := &in.CollectedAt, &out.CollectedAt
		*out = (*in).DeepCopy()
	}
	if in.Pod != nil {
		in, out := &in.Pod, &out.Pod
		*out = new(PodEvidence)
		(*in).DeepCopyInto(*out)
	}
	if in.Workload != nil {
		in, out := &in.Workload, &out.Workload
		*out = new(WorkloadEvidence)
		(*in).DeepCopyInto(*out)
	}
	if in.Node != nil {
		in, out := &in.Node, &out.Node
		*out = new(NodeEvidence)
		**out = **in
	}
	if in.Events != nil {
		in, out := &in.Events, &out.Events
		*out = make([]EventEvidence, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Logs != nil {
		in, out := &in.Logs, &out.Logs
		*out = make([]ContainerLogEvidence, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Dependencies != nil {
		in, out := &in.Dependencies, &out.Dependencies
		*out = new(DependencyEvidence)
		(*in).DeepCopyInto(*out)
	}
	if in.CollectionErrors != nil {
		in, out := &in.CollectionErrors, &out.CollectionErrors
		*out = make([]CollectionError, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvidenceSnapshot.
func (in *EvidenceSnapshot) DeepCopy() *EvidenceSnapshot {
	if in == nil {
		return nil
	}
	out := new(EvidenceSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncidentReport) DeepCopyInto(out *IncidentReport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncidentReport.
func (in *IncidentReport) DeepCopy() *IncidentReport {
	if in == nil {
		return nil
	}
	out := new(IncidentReport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IncidentReport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncidentReportList) DeepCopyInto(out *IncidentReportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]IncidentReport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncidentReportList.
func (in *IncidentReportList) DeepCopy() *IncidentReportList {
	if in == nil {
		return nil
	}
	out := new(IncidentReportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IncidentReportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncidentReportSpec) DeepCopyInto(out *IncidentReportSpec) {
	*out = *in
	if in.Workload != nil {
		in, out := &in.Workload, &out.Workload
		*out = new(WorkloadRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncidentReportSpec.
func (in *IncidentReportSpec) DeepCopy() *IncidentReportSpec {
	if in == nil {
		return nil
	}
	out := new(IncidentReportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncidentReportStatus) DeepCopyInto(out *IncidentReportStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.ResolvedAt != nil {
		in, out := &in.ResolvedAt, &out.ResolvedAt
		*out = (*in).DeepCopy()
	}
	if in.StabilityStartedAt != nil {
		in, out := &in.StabilityStartedAt, &out.StabilityStartedAt
		*out = (*in).DeepCopy()
	}
	if in.AffectedPods != nil {
		in, out := &in.AffectedPods, &out.AffectedPods
		*out = make([]PodRef, len(*in))
		copy(*out, *in)
	}
	if in.Trigger != nil {
		in, out := &in.Trigger, &out.Trigger
		*out = new(TriggerInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.LastFailureAt != nil {
		in, out := &in.LastFailureAt, &out.LastFailureAt
		*out = (*in).DeepCopy()
	}
	if in.Evidence != nil {
		in, out := &in.Evidence, &out.Evidence
		*out = new(EvidenceSnapshot)
		(*in).DeepCopyInto(*out)
	}
	if in.Diagnosis != nil {
		in, out := &in.Diagnosis, &out.Diagnosis
		*out = new(DiagnosisResult)
		(*in).DeepCopyInto(*out)
	}
	if in.Timeline != nil {
		in, out := &in.Timeline, &out.Timeline
		*out = make([]TimelineEvent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CorrelatedEvidence != nil {
		in, out := &in.CorrelatedEvidence, &out.CorrelatedEvidence
		*out = new(CorrelatedEvidence)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncidentReportStatus.
func (in *IncidentReportStatus) DeepCopy() *IncidentReportStatus {
	if in == nil {
		return nil
	}
	out := new(IncidentReportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogPatterns) DeepCopyInto(out *LogPatterns) {
	*out = *in
	if in.ContainerWithPattern != nil {
		in, out := &in.ContainerWithPattern, &out.ContainerWithPattern
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogPatterns.
func (in *LogPatterns) DeepCopy() *LogPatterns {
	if in == nil {
		return nil
	}
	out := new(LogPatterns)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeEvidence) DeepCopyInto(out *NodeEvidence) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeEvidence.
func (in *NodeEvidence) DeepCopy() *NodeEvidence {
	if in == nil {
		return nil
	}
	out := new(NodeEvidence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCEvidence) DeepCopyInto(out *PVCEvidence) {
	*out = *in
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCEvidence.
func (in *PVCEvidence) DeepCopy() *PVCEvidence {
	if in == nil {
		return nil
	}
	out := new(PVCEvidence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodEvidence) DeepCopyInto(out *PodEvidence) {
	*out = *in
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]ContainerEvidence, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InitContainers != nil {
		in, out := &in.InitContainers, &out.InitContainers
		*out = make([]ContainerEvidence, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VolumeMounts != nil {
		in, out := &in.VolumeMounts, &out.VolumeMounts
		*out = make([]VolumeMountEvidence, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodEvidence.
func (in *PodEvidence) DeepCopy() *PodEvidence {
	if in == nil {
		return nil
	}
	out := new(PodEvidence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodRef) DeepCopyInto(out *PodRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodRef.
func (in *PodRef) DeepCopy() *PodRef {
	if in == nil {
		return nil
	}
	out := new(PodRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProbeSummary) DeepCopyInto(out *ProbeSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProbeSummary.
func (in *ProbeSummary) DeepCopy() *ProbeSummary {
	if in == nil {
		return nil
	}
	out := new(ProbeSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SchedulingConstraints) DeepCopyInto(out *SchedulingConstraints) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ResourceRequests != nil {
		in, out := &in.ResourceRequests, &out.ResourceRequests
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SchedulingConstraints.
func (in *SchedulingConstraints) DeepCopy() *SchedulingConstraints {
	if in == nil {
		return nil
	}
	out := new(SchedulingConstraints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimelineEvent) DeepCopyInto(out *TimelineEvent) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimelineEvent.
func (in *TimelineEvent) DeepCopy() *TimelineEvent {
	if in == nil {
		return nil
	}
	out := new(TimelineEvent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TriggerInfo) DeepCopyInto(out *TriggerInfo) {
	*out = *in
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TriggerInfo.
func (in *TriggerInfo) DeepCopy() *TriggerInfo {
	if in == nil {
		return nil
	}
	out := new(TriggerInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeMountEvidence) DeepCopyInto(out *VolumeMountEvidence) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeMountEvidence.
func (in *VolumeMountEvidence) DeepCopy() *VolumeMountEvidence {
	if in == nil {
		return nil
	}
	out := new(VolumeMountEvidence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadCondition) DeepCopyInto(out *WorkloadCondition) {
	*out = *in
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadCondition.
func (in *WorkloadCondition) DeepCopy() *WorkloadCondition {
	if in == nil {
		return nil
	}
	out := new(WorkloadCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadEvidence) DeepCopyInto(out *WorkloadEvidence) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]WorkloadCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadEvidence.
func (in *WorkloadEvidence) DeepCopy() *WorkloadEvidence {
	if in == nil {
		return nil
	}
	out := new(WorkloadEvidence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadRef) DeepCopyInto(out *WorkloadRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadRef.
func (in *WorkloadRef) DeepCopy() *WorkloadRef {
	if in == nil {
		return nil
	}
	out := new(WorkloadRef)
	in.DeepCopyInto(out)
	return out
}
